### ISSUE TITLE
How to set an order_by for models

### ISSUE THREAD

**Issue by zsinnema** [jdkandersson/OpenAlchemy#107]
Is there a way to set an order_by on models and child models?

**Comment by jdkandersson** [comment]
Are you referring to ordering the results of a database query? Here is some documentation for the order_by of the SQLAlchemy query operation: [https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.order_by](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.order_by). The models produced by OpenAlchemy are standard SQLAlchemy models so all SQLAlchemy features, such as order_by, work on the models.

**Comment by zsinnema** [comment]
Yes I know how to set an order_by but it's more about child records
in sqlalchemy you can set a default order for foreign keys/relationships (see https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/relationships.html , order_by="desc(Address.email)")

so I'm wondering how to set/configure this with open alchemy. I couldn't find it here: https://github.com/jdkandersson/OpenAlchemy/blob/b22d0c4b226a38f7010b430bf67192b70bc97152/open_alchemy/facades/sqlalchemy/__init__.py#L38

**Comment by jdkandersson** [comment]
Thanks for clarifying, this makes a lot of sense to include. I will prioritise this next. I will also broaden the issue to examine and potentially include other arguments of the _relationship_ constructor that are not yet supported.

**Comment by jdkandersson** [comment]
A new extension property, _x-kwargs_, is to be added which is a generic object. It is a general extension property that can be used in places where generic kwargs make sense. In the case of properties referencing other objects (which leads to the construction of a relationships), when it is included as a part of the _allOf_ directive, it will be passed to the relationship constructor using dictionary destructing. The keys must be strings. There will be no validity checks on the dictionary values before it is passed to the relationship. The only check that will be performed is that any arguments to the relationship that have a special meaning for OpenAlchemy, such as _backref_, may not appear in _x-kwargs_ and must be defined using the specific extension property for that argument.

**Comment by jdkandersson** [comment]
@zsinnema This feature is now available on the _mater_ branch and will be released with the next version. The following may be useful information:

- Documentation: [https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/relationships.html#other-keyword-arguments](https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/relationships.html#other-keyword-arguments)
- Example: [https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/relationship/many_to_one.html#relationship-kwargs](https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/relationship/many_to_one.html#relationship-kwargs)

**Comment by jdkandersson** [comment]
This feature has been released.
