### ISSUE TITLE
Support `extend_existing` for class inheritance

### ISSUE THREAD

**Issue by jeremander** [jdkandersson/OpenAlchemy#113]
Hello,

Thanks for making this framework; it's great and easy to use!

Suppose I have a spec like:
```
    Log:
      type: object
      description: A log of an event.
      x-tablename: logs
      ...
```
And I want to subclass it to `CreationLog`:
```
    CreationLog:
      description: A log of a creation event.
      allOf:
        - $ref: '#/components/schemas/Log'
        - type: object
          properties:
            creationDate:
              type: string
              format: date-time
```
Then when calling `init_yaml`, I get this error:
```
InvalidRequestError: Table 'logs' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
Ideally what I would want is for `CreationLog` to be a subclass of `Log`, and have a single SQL table `logs` whose columns include all the fields for `CreationLog`. It's somewhat unclear what do in the case where multiple classes inherit from `Log`, but I suppose the most sensible thing would be to have `logs` include all columns present in any of its subclasses.

From the SQLAlchemy docs, it seems like when you create the same Table twice, it will only allow you to extend the table with new fields if you pass `extend_existing=True` to the constructor.

**Comment by jdkandersson** [comment]
Hi @jeremander,

Thanks for putting together a detailed proposal. One question I have, please help me understand, if you moved the `x-tablename` from `Log` to `CreationLog`, would that address the use case? That would ensure that `CreationLog` inherits all properties from `Log` as well as the `creationDate` of `CreationLog`.

I understood that `extend_existing` is a good way to implement inheritance, OpenAlchemy allows you to do that by defining base schemas without `x-tablename` and then using `allOf` like you have to incorporate the base schemas for other schemas.

The only other though that I have is that it would be useful if you needed access to the `Log` class for some other purpose than extending it through other models.

The following documentation may be of use: [https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/inheritance.html](https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/inheritance.html)

The following example may also help you further: [https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/all_of.html](https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/all_of.html)

**Comment by jeremander** [comment]
Thank you!  OK, so your suggestion of moving `x-tablename` to `CreationLog` does work.  This fits in with the use case of your employee/division example where they inherit properties from an `IdNameBase` schema.  I do notice, though, that although schema inheritance happens, there is no Python class-based inheritance taking place.

The use case I'm interested in is "single table inheritance":

https://docs.sqlalchemy.org/en/13/orm/inheritance.html?highlight=single%20table#single-table-inheritance

So in my example, `CreationLog` and `EditLog` would both be schemas inheriting from `Log`, but they would share the same SQL table. Currently f I put `x-tablename: logs` for both of them, I still get the `InvalidRequestError` from before, since it's trying to redefine the same table twice without `extend_existing`.

To make this kind of single table inheritance work, OpenAlchemy would probably need to employ Python-based class inheritance and also add the appropriate `__mapper_args__` to the class definitions, as per the Employee/Manager/Engineer example linked above.  Same could apply to the "joined inheritance" paradigm, where each subclass is associated with a different table.

**Comment by jdkandersson** [comment]
That makes sense, thanks for clarifying.

The proposal is to use #112 for the additional table arguments (eg. `__mapper_args__`). This will also allow users to perform joined table inheritance among a range of other use cases.

Additionally, some way of indicating that an `allOf` without an `x-tablename` should be constructed will also be included, potentially through a new extension parameter. This will need to be reflected in the typed models file.

Concrete table inheritance and abstract concrete classes will not be supported for the moment as there doesn't seem to be an obvious use case that isn't already covered by the current `allOf` functionality.

**Comment by jdkandersson** [comment]
The plan is to add an `x-inherits` extension property which can be a boolean or string. If it is a string, it defines the parent class. This parent class must be somewhere in the inheritance chain in OpenAPI and it must also either have the `x-inherits` or the `x-tablename` extension property. If it is a boolean, the inheritance chain is traversed for the next schema which either has the `x-inherits` or the `x-tablename` extension property.

There is a dependency that the parent must be constructed before the child. This can be achieved by calling the model factory with the parent name.

**Comment by jdkandersson** [comment]
The feature has been implemented.

- Documentation is here: [https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/inheritance.html#joined-table-inheritance](https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/inheritance.html#joined-table-inheritance)
- Example is here: [https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/inheritance.html](https://openapi-sqlalchemy.readthedocs.io/en/latest/examples/inheritance.html)

This will be released with the next version expected later today.

**Comment by jdkandersson** [comment]
This feature has been released.
