### ISSUE TITLE
black linter in `install_requires` in `setup.py` not needed

### ISSUE THREAD

**Issue by guillaumedsde** [jdkandersson/OpenAlchemy#132]
Hi, very useful project thanks :+1: 

I was wondering whether the `black` linter is really a needed runtime dependency as you specified in  `install_requires` in `setup.py` shouldn't this only be a dev dependency?

**Comment by jdkandersson** [comment]
I'm glad you find it useful! Keen to hear about any other features you would like.

On `black`, the reason it is a runtime dependency is that `OpenAlchemy` supports generating a file that contains the SQLAlchemy models with type hints to support IDE auto completion. You can read more about it here: [models file](https://openapi-sqlalchemy.readthedocs.io/en/latest/#models-file). The final step is to apply `black` formatting to the file to ensure it looks good. This is done at runtime.

**Comment by guillaumedsde** [comment]
Ah, makes sense I undestand, thanks for the quick answer :)
