### ISSUE TITLE
Add openalchemy prefix

### ISSUE THREAD

**Issue by jdkandersson** [jdkandersson/OpenAlchemy#165]
As a user I want to avoid clashes with OpenAlchemy's extension properties with other extension property definitions so that I can use my templates for multiple purposes.

Support looking up any `x-...` keys for both the current and `x-open-alchemy-...` version.

**Comment by jdkandersson** [comment]
As a first step, look at the extension properties defined in `open_alchemy/helpers/ext_prop/extension-schemas.json`and look for extension properties that are not all over the code base. For those, change the implementation in `open_alchemy/helpers/peek.py` to use both the `x-...` version and the `x-openalchemy-...` version.

**Comment by rgreinho** [comment]
That makes sense! I am interested to give it a shot.

**Comment by jdkandersson** [comment]
Most of the tests are here: `tests/open_alchemy/helpers/test_peek/test_peek_extension.py`

**Comment by jdkandersson** [comment]
The proposal is to do this for everything in the `open_alchemy/helpers/peek.py` file and then we can look at moving the remaining code base to use these peek functions instead of the key directly/

**Comment by jdkandersson** [comment]
Note that I propose the use of `x-open-alchemy` instead of `x-openalchemy`.
