### ISSUE TITLE
integrating flask_login into OpenAlchemy generated model (User object)

### ISSUE THREAD

**Issue by tduval-unifylogic** [jdkandersson/OpenAlchemy#173]
I notice the 'model' construct of classes is different in what OpenAlchemy generates (seems like dynamic dictionaries cast as objects?)
Anyway, I want to be able to generate dynamic models (using your tool) and want to have each of them have authentication (AND be able to record what user has made what changes to the underlying data). [Found this page for integrating in flask authentication](https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login) (using to get started) and then when i go to this part (where you make the connection between flask_login and the User class in Models, I promptly ran into a brick wall! since there is no 'proper' User class in Models for me to do this. I added one to my schema according to what they outlined in the article (id, email, name, password, etc.), and OpenAlchemy generates it, but not sure how to hook flask_login's UserMixin with it. Any help is appreciated...

if you know a better way to do basic login/authentication with the models resulting from OpenAlchemy - I'm open to a different approach! Thanks!!

Sorry, here's the image of the code on the page I was looking at. Forgot to attach.
[Annotation 2020-08-22 172245](https://user-images.githubusercontent.com/62360524/90966974-bcb67680-e4a6-11ea-890d-dd82eb6172be.png)

**Comment by jdkandersson** [comment]
Yeh I agree, I was thinking the same.
