### ISSUE TITLE
Model import documentation

### ISSUE THREAD

**Issue by jdkandersson** [jdkandersson/OpenAlchemy#178]
As a user I want to easily understand how I can access the model classes so that I can get started quickly.

- [ ] Add a section in the documentation to explain the import behaviour
- [ ] Remove the autogenerated models from the app example

**Comment by rgreinho** [comment]
I am trying to use the `models_autogenerated.py` file that I generated from my openapi specification file, but I get an error when I import the file directly:

![image](https://user-images.githubusercontent.com/6969134/92180314-59183b80-ee0c-11ea-9353-e86a472cac73.png)

It does work correctly, if I import the models using the `init_yaml` function:
![image](https://user-images.githubusercontent.com/6969134/92180450-aa282f80-ee0c-11ea-9dec-0f9338e29b1a.png)

But I would like to understand how I can use the `models_autogenerated.py` instead.

**Comment by jdkandersson** [comment]
Could you please share the OpenAPI spec (or an excerpt from it with the relevant section) that you are using? It would also be great if you could share the autogenerated models file as well.

**Comment by rgreinho** [comment]
Here is the specification file:

```yaml
openapi: "3.0.2"
info:
  title: "Space API"
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths: {}
components:
  schemas:
    space:
      type: object
      x-tablename: spaces
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          x-primary-key: true
          x-autoincrement: true
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
```

And here is the autogenerated models file:

```python
"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member,super-init-not-called,unused-argument

import datetime
import typing

import sqlalchemy
from sqlalchemy import orm

from open_alchemy import models


class _spaceDictBase(typing.TypedDict, total=True):
    """TypedDict for properties that are required."""

    name: str


class spaceDict(_spaceDictBase, total=False):
    """TypedDict for properties that are not required."""

    id: int
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]


class Tspace(typing.Protocol):
    """
    SQLAlchemy model protocol.

    Attrs:
        id: The id of the space.
        name: The name of the space.
        created_at: The created_at of the space.
        updated_at: The updated_at of the space.

    """

    # SQLAlchemy properties
    __table__: sqlalchemy.Table
    __tablename__: str
    query: orm.Query

    # Model properties
    id: "sqlalchemy.Column[int]"
    name: "sqlalchemy.Column[str]"
    created_at: "sqlalchemy.Column[typing.Optional[datetime.datetime]]"
    updated_at: "sqlalchemy.Column[typing.Optional[datetime.datetime]]"

    def __init__(
        self,
        name: str,
        id: typing.Optional[int] = None,
        created_at: typing.Optional[datetime.datetime] = None,
        updated_at: typing.Optional[datetime.datetime] = None,
    ) -> None:
        """
        Construct.

        Args:
            id: The id of the space.
            name: The name of the space.
            created_at: The created_at of the space.
            updated_at: The updated_at of the space.

        """
        ...

    @classmethod
    def from_dict(
        cls,
        name: str,
        id: typing.Optional[int] = None,
        created_at: typing.Optional[datetime.datetime] = None,
        updated_at: typing.Optional[datetime.datetime] = None,
    ) -> "Tspace":
        """
        Construct from a dictionary (eg. a POST payload).

        Args:
            id: The id of the space.
            name: The name of the space.
            created_at: The created_at of the space.
            updated_at: The updated_at of the space.

        Returns:
            Model instance based on the dictionary.

        """
        ...

    @classmethod
    def from_str(cls, value: str) -> "Tspace":
        """
        Construct from a JSON string (eg. a POST payload).

        Returns:
            Model instance based on the JSON string.

        """
        ...

    def to_dict(self) -> spaceDict:
        """
        Convert to a dictionary (eg. to send back for a GET request).

        Returns:
            Dictionary based on the model instance.

        """
        ...

    def to_str(self) -> str:
        """
        Convert to a JSON string (eg. to send back for a GET request).

        Returns:
            JSON string based on the model instance.

        """
        ...


space: typing.Type[Tspace] = models.space  # type: ignore

```

**Comment by jdkandersson** [comment]
I think I know what the problem is. Before the line

```python
s = models.space(name="my_space")
```

you need to include the line

```python
init_yaml('openapi/openapi.yaml')
```

For example, the following should work:

```python
from project.api import models_autogenerated as models
from open_alchemy import init_yaml
init_yaml('openapi/openapi.yml')
s = models.space(name="my_space")
```

The `models_autogenerated` assume that you call `init_yaml` before you interact with the models. I wonder whether that is the right behaviour, do you think `models_autogenerated` should take all the required actions to make them usable? The reason they currently do not is because in some cases (for example, when `flask-sqlalchemy` is in use), the models need to inherit from a specific base. Without allowing the user to call their own `init_yaml` this would not be possible. Maybe there should be a check at the start of `models_autogenerated` for whether `init_yaml` or equivalent has already been run, and if not, run it. Thoughts?

**Comment by rgreinho** [comment]
Oh I see. Our use case is to reuse the models from this specification file in other projects, without having to provide the specification file. Since we had the autogenerated models, we thought we could just import them as is. Otherwise we could explore SQLAlchemy reflection mechanism, but since OpenAlchemy already did all the heavy lifting, we would rather leverage it.

I guess for us, either the check you proposed, or adding another option to `init_yaml`, for instance `standalone=True` would be good. 👍

**Comment by jdkandersson** [comment]
Ah I understand better now. There is another issue I'm working on at the moment, #185, that will create a distribution for models which can then be published on a package index. So it would allow you to install the `SQLAlchemy` models using pip.

**Comment by rgreinho** [comment]
That sounds awesome and looks exactly like what I am looking for! 👍 

Let me know if you I can help with testing or documenting 📚 .
