### ISSUE TITLE
No force of inserts for many-to-one relationships

### ISSUE THREAD

**Issue by MartyStache** [jdkandersson/OpenAlchemy#180]
Hi again! Thanks for your help on the Mixin. Totally got my authentication working wonderfully! 

I have run into another issue with respect to foreign keys and the many-to-one relationships I set in my schema.

If I am using the style outlined in api.py to process the request and my schema is such that, let's say, division is a separate object with a many to one relationship and i'm passing the object in the response with only the name of the division, is there a parameter that I can set to indicate not to try and force inserting 'Finance' as a division when inserting Joe because it was already created prior? I'm experiencing this issue and hope there is a remedy for it?

I would like to be able to use JSON request like:
{
	"name": "George",
	"division": {
		"name": "Engineering"
	}
	"salary": 1000000.00
}

and NOT have a forced insert since the division already exists using the code below. Is there a setting I need to put on the schema?

#API.PY
import database
import models_autogenerated as models

def search():
    """Get all employees from the database."""
    employees = models.Employee.query.all()
    employee_dicts = map(lambda employee: employee.to_dict(), employees)
    return list(employee_dicts)

def post(body):
    """Save an employee to the database."""
    if models.Employee.query.filter_by(id=body["id"]).first() is not None:
        return ("Employee already exists.", 400)
    employee = models.Employee.from_dict(**body)
    database.db.session.add(employee)
    database.db.session.commit()

def get(id):
    """Get an employee from the database."""
    employee = models.Employee.query.filter_by(id=id).first()
    if employee is None:
        return ("Employee not found.", 404)
    return employee.to_dict()

def patch(body, id):
    """Update an employee in the dayabase."""
    employee = models.Employee.query.filter_by(id=id).first()
    if employee is None:
        return ("Employee not found.", 404)
    employee.name = body["name"]
    employee.division = body["division"]
    employee.salary = body["salary"]
    database.db.session.commit()
    return 200

def delete(id):
    """Delete an employee from the database."""
    result = models.Employee.query.filter_by(id=id).delete()
    if not result:
        return ("Employee not found.", 404)
    database.db.session.commit()
    return 200

# HERE IS THE SCHEMA from OPENAPI SPEC

components:
  schemas:
    Division:
      description: A part of a company.
      type: object
      x-tablename: division
      properties:
        id:
          type: integer
          description: Unique identifier for the division.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the division.
          example: Engineering
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
        division:
          "$ref": "#/components/schemas/Division"

**Comment by jdkandersson** [comment]
Hi,

In this case you would need to implement that yourself. I would recommend putting a unique constraint on `name` on the `Division` to ensure that you can't insert duplicates (you can just add `x-unique` to the property).

I would recommend the following approach:

1. When you receive an employee, query the database for the division name.
2. If you don't find the division, just push the employee into the database using `from_dict` and the session and stop execution.
3. Use the employee constructor to build the `Employee` model (use `__init__`, not `from_dict`) and pass in the division you have queried for.
4. Add the employee to the session and commit the session.

**Comment by jdkandersson** [comment]
Please let me know if there is anything else that you need
