### ISSUE TITLE
type:ignore in generated models not working 

### ISSUE THREAD

**Issue by madhamanchiharsha** [jdkandersson/OpenAlchemy#294]
Base = models.base  # type: ignore
AttributeError: module 'models' has no attribute 'base'

this is the error i see when i try to import that model in main.py any help...! 
(my whatsapp number is 7871234304 you can ping me here )

**Comment by jdkandersson** [comment]
Hi, I think if you change to `Base = models.Base` it should work, Please let me know how you go!

**Comment by madhamanchiharsha** [comment]
I have one question where can i give schema name like for example database.session.add(andersonObj) should do something like this INSERT INTO **schema**.anderson (id, name) VALUES (1, '2')

**Comment by jdkandersson** [comment]
Does this work for you? https://stackoverflow.com/questions/24542561/sqlalchemy-query-using-tables-in-two-mysql-schemas

If so, I would need to do an enhancement to the package, at the moment table args are not supported

**Comment by madhamanchiharsha** [comment]
Hi actually some times it is not working
when my peer followed it was working fine for the code shown in open
alchemy website those are examples.
today morning i tried it is not working again.

**Comment by jdkandersson** [comment]
I'm sorry to hear that, could you please share the code and any artefacts that show that it is not working (e.g., error messages)?

**Comment by jdkandersson** [comment]
I have added support for grouping models using schemas, as requested earlier in this issue. You can read the docs for it here: https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/model.html#define-custom-schema-name

**Comment by madhamanchiharsha** [comment]
Thanks, I'll check it out.

**Comment by jdkandersson** [comment]
Closing for now, please reopen if this doesn't solve it for you.
